; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = -std=gnu++17 -DCORE_DEBUG_LEVEL=5
# project dependencies
lib_compat_mode = off
lib_deps = olikraus/U8g2@^2.36.18

[env:esp32-c6-devkitm-1]
platform = platformio/espressif32
framework = espidf
board = esp32-c6-devkitm-1
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:esp32-c3-devkitm-1]
platform = platformio/espressif32
framework = espidf
board = esp32-c3-devkitm-1
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:esp-wroom-02]
# esp8266 build target, experimental
# requires packages: python-pip python-pyparsing
# also requires the manual creation of sdkconfig.esp-wroom-02
platform = https://github.com/freedib/platform-espressif8266.git
platform_packages =
    framework-esp8266-rtos-sdk @ https://github.com/freedib/framework-esp8266-rtos-sdk.git@3.4
    toolchain-xtensa @ https://github.com/freedib/toolchain-xtensa-linux_amd64-8.4.0.git@8.4.0
    tool-genbin-esp8266 @ https://github.com/freedib/tool-genbin-esp8266.git@1.0.0
framework = esp8266-rtos-sdk
build_unflags = -std=gnu++11 -std=c++11
board = esp_wroom_02
monitor_speed = 74880
monitor_filters = esp8266_exception_decoder