; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
# project dependencies
lib_compat_mode = off
lib_deps = olikraus/U8g2@^2.36.18

[env:esp32-c6-devkitm-1]
platform = platformio/espressif32
framework = espidf
board = esp32-c6-devkitm-1
monitor_speed = 115200

[env:esp32-c3-devkitm-1]
platform = platformio/espressif32
framework = espidf
board = esp32-c3-devkitm-1
monitor_speed = 115200

;[env:esp_wroom_02]
;# use custom platform-espressif package, to use a more up to date esp8266-rtos-sdk
;;platform = https://github.com/freedib/platform-espressif8266.git
;platform = espressif8266
;framework = esp8266-rtos-sdk
;;platform_packages =
;;    framework-esp8266-rtos-sdk @ https://github.com/freedib/framework-esp8266-rtos-sdk.git@3.4
;;    toolchain-xtensa @ https://github.com/freedib/toolchain-xtensa-linux_amd64-8.4.0.git@8.4.0
;
;board = esp_wroom_02
;board_build.f_cpu = 160000000L
;monitor_speed = 74880